version: '3'

services:
  api:
    container_name: account_service_api
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_PASSWORD: postgres

  db:
    container_name: account_service_db
    image: postgres:11
    restart: unless-stopped
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: account_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:
