openapi: 3.0.1


info:
  title: Account Service
  description: Service for working with user accounts
  version: 1.4.0


paths:
  /account/{userId}/balance:
    get:
      summary: Get account balance of the user
      parameters:
        - name: userId
          in: path
          description: Id of user whose balance to return
          required: true
          schema:
            type: integer
            format: int64
        - name: currency
          in: query
          description: Currency to represent the balance
          required: false
          example: "USD"
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/OK.Balance'
        400:
          $ref: '#/components/responses/BadRequest'

    put:
      summary: Debiting and crediting from the user balance
      parameters:
        - name: userId
          in: path
          description: Id of user whose balance to operate
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Debit or credit data
        content:
          applciation/json:
            schema:
                type: object
                properties:
                  amount:
                    type: number
                    format: currecny
                  description:
                    type: string
      responses:
        200:
          $ref: '#/components/responses/OK.Balance'
        400:
          $ref: '#/components/responses/BadRequest'

  /account/{userId}/history:
    get:
      summary: Get history of transactions
      parameters:
        - name: userId
          in: path
          description: Id of user whose balance to operate
          required: true
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: Page size
          schema:
            type: integer
        - name: cursor
          in: query
          description: Id from previous fetch for pagination
          schema:
            type: integer
        - name: sort_by
          in: query
          description: Sort key
          schema:
            type: string
            example: date
        - name: order_by
          in: query
          description: Sort order
          schema:
            type: string
            example: date
      responses:
        200:
          $ref: '#/components/responses/OK.History'
        400:
          $ref: '#/components/responses/BadRequest'

  /transfer:
    post:
      summary: Transfering from one account to other
      requestBody:
        $ref: '#/components/requestBodies/Transfer'
      responses:
        200:
          $ref: '#/components/responses/OK.Transfer'
        400:
          $ref: '#/components/responses/BadRequest'


components:
  schemas:
    Account:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        balance:
          type: number
          format: currecny

    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        account_id:
          type: integer
          format: int64
        amount:
          type: number
          format: currecny
        description:
          type: string

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  requestBodies:
    Transfer:
      description: Transfer data
      content:
        application/json:
          schema:
            type: object
            properties:
              debit_user_id:
                type: integer
                format: int64
              credit_user_id:
                type: integer
                format: int64
              amount:
                type: number
                format: currecny
              description:
                type: string

  responses:
    OK.Balance:
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Account'

    OK.Transfer:
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Transaction'
            minItems: 2
            maxItems: 2

    OK.History:
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
              cursor:
                type: integer
                format: int64

    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
